### ISSUE TITLE
"lookup plugin (task_src) not found" error

### ISSUE THREAD

**Issue by MonOttawa** [carlalexander/debops-wordpress#108]
Hi Guys,

Sorry if this may sound repetitive to you, but I can't seem to be able to get around this error when I run the last command `debops wordpress` . I get this error, 

`TASK [debops.postfix : DebOps pre_tasks hook] **********************************
fatal: [extramind.ca]: FAILED! => {"failed": true, "msg": "lookup plugin (task_src) not found"}
	to retry, use: --limit @/Users/admin/Desktop/Sites/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP *********************************************************************
extramind.ca                : ok=19   changed=5    unreachable=0    failed=1
`
I've tried looking around, but the answers I saw was way over my newbie knowledge. What are the steps you guys took to solve this (please be kind)...

I'm running from macOS sierra and using the zsh (if that matters at all)...

Cheers,
MO

**Comment by carlalexander** [comment]
Have you tried this [workaround](https://github.com/carlalexander/debops-wordpress/wiki/Known-issues#lookup-plugin-task_src-not-found) from the wiki?

**Comment by MonOttawa** [comment]
Muchas gracias Carl... that did the trick! Thanks for the amazing work here..

**Comment by MonOttawa** [comment]
Hi Carl,

I'm not sure what's happening here, but I now get this message error:

TASK [debops.php : Install PHP packages] ***************************************
failed: [metaneurons.com](item=[u'php5-cli', u'php5-fpm', u'php5', u'php5-curl', u'php5-gd', u'php5-mcrypt', u'php5-mysql', u'php5-curl', u'php5-dev', u'php-redis', u'xml']) => {"failed": true, "item": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php-redis", "xml"], "msg": "No package matching 'php-redis' is available"}

I tried it on two different brand new ubuntu lts server... I'm not using digitalocean, but confirm that the ssh keys are set properly along with hostname...

**Comment by carlalexander** [comment]
Let me look into this over the weekend and get back to you 😄

**Comment by MonOttawa** [comment]
Hi Carl,

I tried to repeat this again and still stuck with the same error ... any clues?

thanks,
MO

**Comment by carlalexander** [comment]
Should be working now. Just need update the project to use the `v0.3.1` tag!

**Comment by MonOttawa** [comment]
Sorry Carl, but I still get the same error again ...

TASK [debops.php : Get available PHP packages for selected version] ************
[DEPRECATION WARNING]: always_run is deprecated. Use check_mode = no instead..
This feature will be removed in version 2.4. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
ok: [metaneurons.com]

TASK [debops.php : Install PHP packages] ***************************************
failed: [metaneurons.com](item=[u'php5-cli', u'php5-fpm', u'php5', u'php5-curl', u'php5-gd', u'php5-mcrypt', u'php5-mysql', u'php5-curl', u'php5-dev', u'php5-redis', u'xml']) => {"failed": true, "item": ["php5-cli", "php5-fpm", "php5", "php5-curl", "php5-gd", "php5-mcrypt", "php5-mysql", "php5-curl", "php5-dev", "php5-redis", "xml"], "msg": "No package matching 'xml' is available"}
    to retry, use: --limit @/Users/admin/Desktop/Sites/debops-wordpress/playbooks/wordpress.retry

I did use the 
'git checkout tags/v0.3.1'

**Comment by carlalexander** [comment]
No worries @MonOttawa! It's not the same error this time. Before it was `php-redis`, this time it says `xml`. I did a test run of this on a DO droplet yesterday and didn't get this error.

Could you tell me a bit more about the ubuntu version and the host that you're using. 😄

**Comment by MonOttawa** [comment]
Thanks Carl your help, here's the setup I have:
- The host is cloudatcost.com
- The server is an ubuntu LTS 14.04
- I'm running Ansible from a desktop Imac with macOS sierra...

Please let me know if you need more info and thanks for your patience ... I'm a complete newbie here...

MO

**Comment by carlalexander** [comment]
That's the issue. Since version `0.3.0`, the project only supports 16.04 LTS (the new LTS version). If you can create a server with that version, you should be ok! 😄

**Comment by MonOttawa** [comment]
Thanks!!! Unfortunately, my host here can only spin LTS 14.04 ... Will try to find a server with 16.04 LTS) ... Thanks a lot for your help... I should still be using tags/v0.3.1 from now on... right?

**Comment by carlalexander** [comment]
Yep!

**Comment by harikrishnanr994** [comment]
ERROR....

Cannot proceed further.

TASK [debops.users : DebOps pre_tasks hook] *****************************************************************************************************************************************
fatal: [example.com]: FAILED! => {"failed": true, "msg": "lookup plugin (task_src) not found"}
	to retry, use: --limit @/Users/xxx/debops-wordpress/playbooks/wordpress.retry

PLAY RECAP **************************************************************************************************************************************************************************
example.com      : ok=40   changed=0    unreachable=0    failed=1

**Comment by carlalexander** [comment]
Have you tried [this](https://github.com/carlalexander/debops-wordpress/wiki/Known-issues#lookup-plugin-task_src-not-found)?
