### ISSUE TITLE
Blank screen

### ISSUE THREAD

**Issue by carlalexander** [carlalexander/debops-wordpress#13]
There's a few situations that seem to cause blank pages from WordPress. It doesn't seem like the request wasn't received. Instead, it seems like there's no HTML sent. Or maybe it's a redirect response that doesn't make it to the browser.

Investigate blank screen for:
- [ ] Installing a new plugin from the admin
- [ ] Importing XML
- [ ] Core update

**Comment by carlalexander** [comment]
Created and destroyed a DO droplet a few times to try reproducing the issue. So far, I've seen it once. Couldn't see anything wrong from the nginx side. Forgot to turn on `varnishlog`.

**Comment by shawnhooper** [comment]
The only time I've seen this was with the simple-fields plugin. It was causing a white screen (and only on my production box, not staging) when it called it's internal clear_cache function.  Wasn't a plugin conflict, it would do this even if it was the only plugin installed.

I opened a support ticket with the plugin's author to see if they would comment: https://wordpress.org/support/topic/clear_caches-causing-wsod?replies=1

**Comment by tobeycodes** [comment]
@carlalexander I get this with any plugin install. Happy to give you ssh access to do your thing and check the logs

**Comment by carlalexander** [comment]
If you're getting this every time, that'd be great. I'm a bit busy this week because I'm speaking at WordCamp Toronto next weekend. I'll reach out over Twitter to get the details.

**Comment by Ichag** [comment]
It seams that the install process of plugins is completed correctly, despite blank screen.

**Comment by carlalexander** [comment]
Yes, that's the issue I observed as well. My hunch is that it's a bug inside the Varnish configuration. Something gets cached and we get that back instead of the redirect. It's just hard to reproduce.

**Comment by carlalexander** [comment]
Ran into a similar issue today doing tests for #29.

Couldn't get the `/wp-login` screen to display with Varnish. Turning off the Varnish server and going to the direct PHP fallback worked. Since I could reproduce the issue consistently, I managed to get some log output. This is from a forced refresh of the page.

``` console
# varnishlog output

*   << Request  >> 32782
-   Begin          req 32781 rxreq
-   Timestamp      Start: 1444590881.251594 0.000000 0.000000
-   Timestamp      Req: 1444590881.251594 0.000000 0.000000
-   ReqStart       127.0.0.1 59608
-   ReqMethod      GET
-   ReqURL         /wp-login.php
-   ReqProtocol    HTTP/1.0
-   ReqHeader      X-Real-IP: 192.222.155.108
-   ReqHeader      X-Forwarded-For: 192.222.155.108
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      X-Forwarded-Port: 443
-   ReqHeader      Host: dev.carlalexander.ca
-   ReqHeader      Connection: close
-   ReqHeader      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:28.0) Gecko/20100101 Firefox/28.0
-   ReqHeader      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   ReqHeader      Accept-Language: en-US,en;q=0.5
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      Cookie: wordpress_test_cookie=WP+Cookie+check
-   ReqHeader      Pragma: no-cache
-   ReqHeader      Cache-Control: no-cache
-   ReqUnset       X-Forwarded-For: 192.222.155.108
-   ReqHeader      X-Forwarded-For: 192.222.155.108, 127.0.0.1
-   VCL_call       RECV
-   ReqUnset       Host: dev.carlalexander.ca
-   ReqHeader      Host: dev.carlalexander.ca
-   ReqUnset       Cookie: wordpress_test_cookie=WP+Cookie+check
-   ReqHeader      Cookie: wordpress_test_cookie=WP+Cookie+check
-   ReqUnset       Cookie: wordpress_test_cookie=WP+Cookie+check
-   ReqHeader      Cookie: wordpress_test_cookie=WP+Cookie+check
-   ReqUnset       Cookie: wordpress_test_cookie=WP+Cookie+check
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   VCL_return     purge
-   ReqUnset       Accept-Encoding: gzip, deflate
-   ReqHeader      Accept-Encoding: gzip
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       PURGE
-   ReqHeader      X-Purge: Yes
-   VCL_return     restart
-   Timestamp      Restart: 1444590881.251716 0.000122 0.000122
-   Link           req 32783 restart
-   End

*   << BeReq    >> 32784
-   Begin          bereq 32783 pass
-   Timestamp      Start: 1444590881.251819 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /wp-login.php
-   BereqProtocol  HTTP/1.0
-   BereqHeader    X-Real-IP: 192.222.155.108
-   BereqHeader    X-Forwarded-Proto: https
-   BereqHeader    X-Forwarded-Port: 443
-   BereqHeader    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:28.0) Gecko/20100101 Firefox/28.0
-   BereqHeader    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   BereqHeader    Accept-Language: en-US,en;q=0.5
-   BereqHeader    Pragma: no-cache
-   BereqHeader    Cache-Control: no-cache
-   BereqHeader    X-Forwarded-For: 192.222.155.108, 127.0.0.1
-   BereqHeader    Accept-Encoding: gzip
-   BereqHeader    X-Purge: Yes
-   BereqHeader    Host: dev.carlalexander.ca
-   BereqHeader    X-Varnish: 32784
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendOpen    18 boot.webserver 127.0.0.1 8080 127.0.0.1 46738
-   Timestamp      Bereq: 1444590881.251972 0.000153 0.000153
-   Timestamp      Beresp: 1444590881.265187 0.013368 0.013215
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Server: nginx
-   BerespHeader   Date: Sun, 11 Oct 2015 19:14:41 GMT
-   BerespHeader   Content-Type: text/html; charset=UTF-8
-   BerespHeader   Connection: close
-   BerespHeader   X-Powered-By: HHVM/3.9.1
-   BerespHeader   Content-Encoding: gzip
-   BerespHeader   Set-Cookie: wordpress_test_cookie=WP+Cookie+check; path=/
-   BerespHeader   Expires: Wed, 11 Jan 1984 05:00:00 GMT
-   BerespHeader   Cache-Control: no-cache, must-revalidate, max-age=0
-   BerespHeader   Vary: Accept-Encoding
-   BerespHeader   Pragma: no-cache
-   BerespHeader   X-Frame-Options: SAMEORIGIN
-   BerespHeader   X-Clacks-Overhead: GNU Terry Pratchett
-   TTL            RFC 0 10 -1 1444590881 1444590881 1444590881 442645200 0
-   VCL_call       BACKEND_RESPONSE
-   TTL            VCL 120 10 0 1444590881
-   VCL_return     deliver
-   Storage        malloc Transient
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Server: nginx
-   ObjHeader      Date: Sun, 11 Oct 2015 19:14:41 GMT
-   ObjHeader      Content-Type: text/html; charset=UTF-8
-   ObjHeader      X-Powered-By: HHVM/3.9.1
-   ObjHeader      Content-Encoding: gzip
-   ObjHeader      Set-Cookie: wordpress_test_cookie=WP+Cookie+check; path=/
-   ObjHeader      Expires: Wed, 11 Jan 1984 05:00:00 GMT
-   ObjHeader      Cache-Control: no-cache, must-revalidate, max-age=0
-   ObjHeader      Vary: Accept-Encoding
-   ObjHeader      Pragma: no-cache
-   ObjHeader      X-Frame-Options: SAMEORIGIN
-   ObjHeader      X-Clacks-Overhead: GNU Terry Pratchett
-   Fetch_Body     0 none -
-   BackendClose   18 boot.webserver
-   Timestamp      BerespBody: 1444590881.265266 0.013447 0.000080
-   Length         0
-   BereqAcct      480 0 480 442 0 442
-   End

*   << Request  >> 32783
-   Begin          req 32782 restart
-   Timestamp      Start: 1444590881.251716 0.000122 0.000000
-   ReqStart       127.0.0.1 59608
-   ReqMethod      GET
-   ReqURL         /wp-login.php
-   ReqProtocol    HTTP/1.0
-   ReqHeader      X-Real-IP: 192.222.155.108
-   ReqHeader      X-Forwarded-Proto: https
-   ReqHeader      X-Forwarded-Port: 443
-   ReqHeader      Connection: close
-   ReqHeader      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:28.0) Gecko/20100101 Firefox/28.0
-   ReqHeader      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   ReqHeader      Accept-Language: en-US,en;q=0.5
-   ReqHeader      Pragma: no-cache
-   ReqHeader      Cache-Control: no-cache
-   ReqHeader      X-Forwarded-For: 192.222.155.108, 127.0.0.1
-   ReqHeader      Host: dev.carlalexander.ca
-   ReqHeader      Accept-Encoding: gzip
-   ReqHeader      X-Purge: Yes
-   VCL_call       RECV
-   ReqUnset       Host: dev.carlalexander.ca
-   ReqHeader      Host: dev.carlalexander.ca
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   ReqHeader      Cookie:
-   ReqUnset       Cookie:
-   VCL_return     pass
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       PASS
-   VCL_return     fetch
-   Link           bereq 32784 pass
-   Timestamp      Fetch: 1444590881.265278 0.013684 0.013562
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Server: nginx
-   RespHeader     Date: Sun, 11 Oct 2015 19:14:41 GMT
-   RespHeader     Content-Type: text/html; charset=UTF-8
-   RespHeader     X-Powered-By: HHVM/3.9.1
-   RespHeader     Content-Encoding: gzip
-   RespHeader     Set-Cookie: wordpress_test_cookie=WP+Cookie+check; path=/
-   RespHeader     Expires: Wed, 11 Jan 1984 05:00:00 GMT
-   RespHeader     Cache-Control: no-cache, must-revalidate, max-age=0
-   RespHeader     Vary: Accept-Encoding
-   RespHeader     Pragma: no-cache
-   RespHeader     X-Frame-Options: SAMEORIGIN
-   RespHeader     X-Clacks-Overhead: GNU Terry Pratchett
-   RespHeader     X-Varnish: 32783
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: MISS
-   RespHeader     X-Cache-Hits: 0
-   RespUnset      X-Powered-By: HHVM/3.9.1
-   RespUnset      Server: nginx
-   RespUnset      X-Varnish: 32783
-   RespUnset      Via: 1.1 varnish-v4
-   RespUnset      X-Clacks-Overhead: GNU Terry Pratchett
-   VCL_return     deliver
-   Timestamp      Process: 1444590881.265309 0.013715 0.000031
-   RespHeader     Accept-Ranges: bytes
-   RespHeader     Content-Length: 0
-   Debug          "RES_MODE 2"
-   RespHeader     Connection: close
-   Timestamp      Resp: 1444590881.265333 0.013739 0.000024
-   ReqAcct        512 0 512 442 0 442
-   End

*   << Session  >> 32781
-   Begin          sess 0 HTTP/1
-   SessOpen       127.0.0.1 59608 *:6081 127.0.0.1 6081 1444590881.251538 15
-   Link           req 32782 rxreq
-   SessClose      RESP_CLOSE 0.014
-   End
```

``` log
# /var/log/nginx/varnish.dev.carlalexander.ca_access.log

192.168.155.108 - - [11/Oct/2015:19:14:41 +0000] "GET /wp-login.php HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:28.0) Gecko/20100101 Firefox/28.0"
```

``` log
# /var/log/nginx/dev.carlalexander.ca_access.log

127.0.0.1 - - [11/Oct/2015:19:14:41 +0000] "GET /wp-login.php HTTP/1.0" 200 1144 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:28.0) Gecko/20100101 Firefox/28.0"
```

The big thing that stands out is the content length. Everything on the Varnish side says that it's `0`. That said, the access log from PHP shows a content length of `1144`. I haven't been able to find anything on that, but this seems quite bizarre.

The only thing that's weird with this is that I only reproduced this using the `4.1` version. Reverting back to `4.0` fixed the issue it seems. Anyways, this might give us a bit of an idea of what's going on.

**Comment by carlalexander** [comment]
I haven't had this issue happen in the past two month during testing other PRs. I'll reopen it if I see it again.

**Comment by carlalexander** [comment]
Was too hasty closing this one. Ran a battery of tests to be sure. I think I was able to see issue. There was a `FetchError eof socket fail` when I checked the `varnishlog`. I'm not sure what it means though since there's no other errors anywhere else. The nginx log is fine and returns a non-empty response.

```
127.0.0.1 - - [21/Nov/2015:23:47:22 +0000] "GET /wp-admin/network/update.php?action=install-plugin&plugin=varnish-http-purge&_wpnonce=d00b6687cd HTTP/1.0" 200 3631 "http://dev.carlalexander.ca/wp-admin/network/plugin-install.php?tab=search&s=varnish" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0"
```

```
*   << BeReq    >> 32819
-   Begin          bereq 32818 pass
-   Timestamp      Start: 1448149639.028154 0.000000 0.000000
-   BereqMethod    GET
-   BereqURL       /wp-admin/network/update.php?action=install-plugin&plugin=varnish-http-purge&_wpnonce=d00b6687cd
-   BereqProtocol  HTTP/1.0
-   BereqHeader    X-Real-IP: 192.222.155.108
-   BereqHeader    X-Forwarded-Proto: http
-   BereqHeader    X-Forwarded-Port: 80
-   BereqHeader    User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0
-   BereqHeader    Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   BereqHeader    Accept-Language: en-US,en;q=0.5
-   BereqHeader    Accept-Encoding: gzip, deflate
-   BereqHeader    Referer: http://dev.carlalexander.ca/wp-admin/network/plugin-install.php?tab=search&s=varnish
-   BereqHeader    X-Forwarded-For: 192.222.155.108, 127.0.0.1
-   BereqHeader    Host: dev.carlalexander.ca
-   BereqHeader    Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   BereqHeader    X-Varnish: 32819
-   VCL_call       BACKEND_FETCH
-   VCL_return     fetch
-   BackendOpen    17 webserver(127.0.0.1,,8080) 127.0.0.1 40260
-   Backend        17 vdir webserver(127.0.0.1,,8080)
-   Timestamp      Bereq: 1448149639.028299 0.000144 0.000144
-   Timestamp      Beresp: 1448149640.184143 1.155989 1.155844
-   BerespProtocol HTTP/1.1
-   BerespStatus   200
-   BerespReason   OK
-   BerespHeader   Server: nginx
-   BerespHeader   Date: Sat, 21 Nov 2015 23:47:20 GMT
-   BerespHeader   Content-Type: text/html; charset=UTF-8
-   BerespHeader   Connection: close
-   BerespHeader   X-Powered-By: HHVM/3.10.1
-   BerespHeader   Content-Encoding: gzip
-   BerespHeader   Set-Cookie: wp-settings-1=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
-   BerespHeader   Set-Cookie: wp-settings-time-1=1448149639; expires=Sun, 20-Nov-2016 23:47:19 GMT; Max-Age=31536000; path=/
-   BerespHeader   Expires: Wed, 11 Jan 1984 05:00:00 GMT
-   BerespHeader   Cache-Control: no-cache, must-revalidate, max-age=0
-   BerespHeader   Vary: Accept-Encoding
-   BerespHeader   Pragma: no-cache
-   BerespHeader   X-Frame-Options: SAMEORIGIN
-   BerespHeader   X-Clacks-Overhead: GNU Terry Pratchett
-   TTL            RFC 0 -1 -1 1448149640 1448149640 1448149640 442645200 0
-   VCL_call       BACKEND_RESPONSE
-   TTL            VCL 120 10 0 1448149640
-   VCL_return     deliver
-   Storage        malloc Transient
-   ObjProtocol    HTTP/1.1
-   ObjStatus      200
-   ObjReason      OK
-   ObjHeader      Server: nginx
-   ObjHeader      Date: Sat, 21 Nov 2015 23:47:20 GMT
-   ObjHeader      Content-Type: text/html; charset=UTF-8
-   ObjHeader      X-Powered-By: HHVM/3.10.1
-   ObjHeader      Content-Encoding: gzip
-   ObjHeader      Set-Cookie: wp-settings-1=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
-   ObjHeader      Set-Cookie: wp-settings-time-1=1448149639; expires=Sun, 20-Nov-2016 23:47:19 GMT; Max-Age=31536000; path=/
-   ObjHeader      Expires: Wed, 11 Jan 1984 05:00:00 GMT
-   ObjHeader      Cache-Control: no-cache, must-revalidate, max-age=0
-   ObjHeader      Vary: Accept-Encoding
-   ObjHeader      Pragma: no-cache
-   ObjHeader      X-Frame-Options: SAMEORIGIN
-   ObjHeader      X-Clacks-Overhead: GNU Terry Pratchett
-   Fetch_Body     4 eof stream
-   FetchError     Resource temporarily unavailable
-   FetchError     eof socket fail
-   Gzip           u F - 0 0 0 0 0
-   BackendClose   17 webserver(127.0.0.1,,8080)
-   BereqAcct      1009 0 1009 585 0 585
-   End

*   << Request  >> 32818
-   Begin          req 32817 rxreq
-   Timestamp      Start: 1448149639.027924 0.000000 0.000000
-   Timestamp      Req: 1448149639.027924 0.000000 0.000000
-   ReqStart       127.0.0.1 47219
-   ReqMethod      GET
-   ReqURL         /wp-admin/network/update.php?action=install-plugin&plugin=varnish-http-purge&_wpnonce=d00b6687cd
-   ReqProtocol    HTTP/1.0
-   ReqHeader      Host: dev.carlalexander.ca
-   ReqHeader      X-Real-IP: 192.222.155.108
-   ReqHeader      X-Forwarded-For: 192.222.155.108
-   ReqHeader      X-Forwarded-Proto: http
-   ReqHeader      X-Forwarded-Port: 80
-   ReqHeader      Connection: close
-   ReqHeader      User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:42.0) Gecko/20100101 Firefox/42.0
-   ReqHeader      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
-   ReqHeader      Accept-Language: en-US,en;q=0.5
-   ReqHeader      Accept-Encoding: gzip, deflate
-   ReqHeader      Referer: http://dev.carlalexander.ca/wp-admin/network/plugin-install.php?tab=search&s=varnish
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_test_cookie=WP+Cookie+check; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969;
-   ReqUnset       X-Forwarded-For: 192.222.155.108
-   ReqHeader      X-Forwarded-For: 192.222.155.108, 127.0.0.1
-   VCL_call       RECV
-   ReqUnset       Host: dev.carlalexander.ca
-   ReqHeader      Host: dev.carlalexander.ca
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_test_cookie=WP+Cookie+check; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969;
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_test_cookie=WP+Cookie+check; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969;
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_test_cookie=WP+Cookie+check; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969;
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_test_cookie=WP+Cookie+check; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969;
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_test_cookie=WP+Cookie+check; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969;
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqUnset       Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   ReqHeader      Cookie: wp-settings-time-1=1448149623; wordpress_b558cb26904621fb11ba8ee5c0adf458=admin%7C1448322245%7CNeAqmQQs3jj9dSBzFrG6GHoSl4MjrYVr17VJL3ej6NF%7C8731272c9d64e1faed5f9eaef69aa873fa57124b21d1430942ecb182432cc969; wordpress_logged_in_b558cb26904621fb11b
-   VCL_return     pass
-   VCL_call       HASH
-   VCL_return     lookup
-   VCL_call       PASS
-   VCL_return     fetch
-   Link           bereq 32819 pass
-   Timestamp      Fetch: 1448149640.184318 1.156394 1.156394
-   RespProtocol   HTTP/1.1
-   RespStatus     200
-   RespReason     OK
-   RespHeader     Server: nginx
-   RespHeader     Date: Sat, 21 Nov 2015 23:47:20 GMT
-   RespHeader     Content-Type: text/html; charset=UTF-8
-   RespHeader     X-Powered-By: HHVM/3.10.1
-   RespHeader     Content-Encoding: gzip
-   RespHeader     Set-Cookie: wp-settings-1=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; Max-Age=0; path=/
-   RespHeader     Set-Cookie: wp-settings-time-1=1448149639; expires=Sun, 20-Nov-2016 23:47:19 GMT; Max-Age=31536000; path=/
-   RespHeader     Expires: Wed, 11 Jan 1984 05:00:00 GMT
-   RespHeader     Cache-Control: no-cache, must-revalidate, max-age=0
-   RespHeader     Vary: Accept-Encoding
-   RespHeader     Pragma: no-cache
-   RespHeader     X-Frame-Options: SAMEORIGIN
-   RespHeader     X-Clacks-Overhead: GNU Terry Pratchett
-   RespHeader     X-Varnish: 32818
-   RespHeader     Age: 0
-   RespHeader     Via: 1.1 varnish-v4
-   VCL_call       DELIVER
-   RespHeader     X-Cache: MISS
-   RespHeader     X-Cache-Hits: 0
-   RespUnset      X-Powered-By: HHVM/3.10.1
-   RespUnset      Server: nginx
-   RespUnset      X-Varnish: 32818
-   RespUnset      Via: 1.1 varnish-v4
-   RespUnset      X-Clacks-Overhead: GNU Terry Pratchett
-   VCL_return     deliver
-   Timestamp      Process: 1448149640.184345 1.156420 0.000027
-   Debug          "RES_MODE 4"
-   RespHeader     Connection: close
-   RespHeader     Accept-Ranges: bytes
-   Timestamp      Resp: 1448149642.181973 3.154049 1.997629
-   Debug          "XXX REF 1"
-   ReqAcct        1038 0 1038 565 0 565
-   End
```

**Comment by carlalexander** [comment]
Now that I have working Docker container. I'm seeing this issue a lot more. It'll be easier to look for a fix.

**Comment by carlalexander** [comment]
I've now spent a ton of hours debugging this issue. The only workaround that works is to use `return(pipe)` instead of `return(pass)` in the varnish configuration. I've [posted about this](https://www.varnish-cache.org/lists/pipermail/varnish-misc/2016-September/025280.html) on the Varnish mailing list. Next step is to create a ticket in the Varnish project itself.

**Comment by zedrickvillas** [comment]
HI i've encountered this also with one of my site.
Is the fix available?

**Comment by carlalexander** [comment]
This issue is still there. I still haven't written the detailed ticket to the varnish team. Are you getting it constantly?

**Comment by tobeycodes** [comment]
I actually get it a ton now. The jetpack and redis plugin although function correctly none of the settings pages load for me

**Comment by carlalexander** [comment]
Alright, I'll look into writing that ticket for the varnish team.

**Comment by cyrrill** [comment]
HI @carlalexander , I'm getting this issue, and using `pipe` rather than `pass` fixes it for me. Did the ticket manage to get posted? Thanks

**Comment by carlalexander** [comment]
No, I've been too busy to start the process sorry 😞
